'use strict';
const $=s=>document.querySelector(s);
const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let token='',state={Devices:[],Alerts:[],ActiveAlerts:0,Topology:{},Trend:[],Links:[]},view='overview',filter='all',selected=null,detail=null,refreshing=false,toastTimer,lastFingerprint='',devicePage=1;
const names={overview:'监控总览',topology:'网络拓扑',devices:'设备管理',alerts:'告警中心',guide:'接入与说明'};
const time=t=>t?new Date(t).toLocaleString('zh-CN',{hour12:false}):'—';
const shortTime=t=>t?new Date(t).toLocaleTimeString('zh-CN',{hour12:false}):'—';
const value=(v,unit='',digits=1)=>v===null||v===undefined?'—':Number(v).toFixed(digits)+unit;
function updateMetricHelp(){}
function rate(n){if(n===null||n===undefined)return '—';if(n<1000)return n.toFixed(0)+' bps';if(n<1e6)return (n/1e3).toFixed(1)+' Kbps';if(n<1e9)return (n/1e6).toFixed(1)+' Mbps';return (n/1e9).toFixed(2)+' Gbps';}
function uptime(t){if(t==null)return '—';let sec=Math.floor(t/100);return Math.floor(sec/86400)+' 天 '+Math.floor(sec%86400/3600)+' 小时';}
function status(d,s){return !d.Enabled?'paused':(s?.Status||'pending');}
function badge(d,s){let k=status(d,s),label={online:'在线',degraded:'SNMP 异常',offline:'未响应',pending:'等待采集',paused:'已暂停'}[k]||'未知';return `<span class="badge ${k}">${label}</span>`;}
function toast(text){$('#toast').textContent=text;$('#toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),4500);}
async function api(path,data){let options={headers:{'X-NetWatch-Token':token}};if(data!==undefined){options.method='POST';options.headers['Content-Type']='application/json';options.body=JSON.stringify(data);}let r=await fetch('/api/'+path,options);if(!r.ok){let error=await r.json().catch(()=>({Error:'服务请求失败'}));throw Error(error.Error||'服务请求失败');}return r.json();}
async function refresh(){if(refreshing)return;refreshing=true;try{state=await api('dashboard');topologyPositions={...(state.Topology||{})};saveTopologyPositions();if(selected){try{detail=await api('device?id='+encodeURIComponent(selected));}catch{selected=null;detail=null;}}const fingerprint=JSON.stringify([state.Devices,state.Alerts,state.Warning,state.Topology,selected,detail,Math.floor(Date.now()/60000)]);if(fingerprint!==lastFingerprint&&!$('#deviceDialog').open&&!topologyDrag){const positions=[...document.querySelectorAll('.table-wrap')].map(e=>e.scrollLeft);render();document.querySelectorAll('.table-wrap').forEach((e,i)=>e.scrollLeft=positions[i]||0);lastFingerprint=fingerprint;}$('#connection').textContent='采集服务已连接';$('#connection').classList.remove('bad');$('#updated').textContent='界面更新于 '+new Date().toLocaleTimeString('zh-CN',{hour12:false});}catch(e){lastFingerprint='';$('#connection').textContent='服务未连接';$('#connection').classList.add('bad');$('#notice').textContent='连接中断：请确认托盘中的 NetWatch 正在运行。'+e.message;$('#notice').classList.remove('hidden');}finally{refreshing=false;}}
function render(){
 $('#breadcrumb').textContent=selected?'设备详情':names[view];
 $('#pageTitle').textContent=selected?'设备运行详情':({overview:'网络运行，一目了然。',topology:'网络拓扑，状态尽在图中。',devices:'管理每一台网络设备。',alerts:'关注值得处理的变化。',guide:'从第一台设备开始。'}[view]);
 $('#pageSubtitle').textContent=({overview:'集中查看交换机、路由器与防火墙的运行状态。',topology:'按设备清单展示当前状态；点击节点可查看详情。',devices:'通过 SNMP v2c 只读采集，按设备设置轮询周期。',alerts:'连续三次采集失败触发设备告警，恢复后自动关闭。',guide:'了解接入方式、指标含义与本机运行设置。'}[view]);
 $('.filterbar').classList.toggle('hidden',!!selected||!['overview','devices'].includes(view));
 $('#stats').classList.toggle('hidden',!!selected||view==='guide');
 document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
 $('#alertBadge').textContent=state.ActiveAlerts;
 let warnings=[];if(state.Warning)warnings.push(state.Warning);if(state.Devices.some(x=>x.Config.Demo))warnings.push('演示设备的数据为模拟值，不代表真实网络状态。');
 let stale=state.Devices.filter(x=>x.Config.Enabled&&x.Current&&Date.now()-x.Current.Time>Math.max(180000,x.Config.Interval*3000));if(stale.length)warnings.push(stale.length+' 台设备的数据已过期，请检查采集服务。');
 $('#notice').textContent=warnings.join(' ');$('#notice').classList.toggle('hidden',!warnings.length);
 renderStats();
 if(selected&&detail){renderDetail();return;}
 if(view==='topology'){renderTopology();return;}
 if(view==='guide'){renderGuide();return;}
 if(view==='alerts'){$('#content').innerHTML=alertsPanel(state.Alerts,false);return;}
 renderDevices();
}
function renderStats(){let online=state.Devices.filter(x=>status(x.Config,x.Current)==='online').length,problems=state.Devices.filter(x=>['offline','degraded'].includes(status(x.Config,x.Current))).length;let measured=state.Devices.filter(x=>x.Config.Enabled&&x.Current?.Snmp&&x.Current.InBps!=null);let total=measured.length?measured.reduce((a,x)=>a+x.Current.InBps,0):null;$('#stats').innerHTML=[['设备总数',state.Devices.length,'台','覆盖交换机 / 路由器 / 防火墙','◫'],['正常在线',online,'台',problems?`${problems} 台设备需关注`:'当前已登记设备的 SNMP 状态','✓'],['端口入方向合计',rate(total),'','所有已采集接口求和，可能重复计流','↙'],['未恢复告警',state.ActiveAlerts,'条','确认告警后仍保留恢复状态','♧']].map(([label,n,unit,foot,icon])=>`<article class="stat"><div class="stat-top">${label}<span class="stat-icon">${icon}</span></div><div class="stat-value">${n}<small>${unit}</small></div><div class="stat-foot">${foot}</div></article>`).join('');}
function filteredDevices(){let q=$('#search').value.toLowerCase(),kind=$('#typeFilter').value;return state.Devices.filter(x=>{let k=status(x.Config,x.Current);return (!kind||x.Config.Type===kind)&&(!q||[x.Config.Name,x.Config.Address,x.Config.Location].join(' ').toLowerCase().includes(q))&&(filter==='all'||(filter==='online'&&k==='online')||(filter==='problem'&&['offline','degraded'].includes(k)));});}
function renderDevices(){
 if(state.Devices.length===0){$('#content').innerHTML=`<section class="panel empty"><div class="empty-orbit">⌁</div><h2>让网络状态变得清晰</h2><p>添加交换机、路由器或防火墙的管理 IP 和只读社区字符串，即可开始查看流量、端口状态与告警。</p><button class="button primary" data-action="add">＋ 添加第一台设备</button> <button class="button" data-action="demo">体验演示数据</button><div class="empty-steps"><span><b>1</b>设备开启 SNMP</span><span><b>2</b>填写连接信息</span><span><b>3</b>自动采集与告警</span></div></section>`;return;}
 let devices=filteredDevices();let rows=devices.map(x=>{let d=x.Config,s=x.Current;return `<tr><td><div class="device-title"><span class="device-icon">${d.Type==='交换机'?'▤':d.Type==='路由器'?'⌁':'◇'}</span><div><a href="#device-${d.Id}" data-action="detail" data-id="${d.Id}" class="device-name">${escapeHTML(d.Name)}</a><div class="cell-sub">${escapeHTML(d.Location||'未设置位置')}${d.Demo?'<span class="badge demo">演示</span>':''}</div></div></div></td><td><span class="mono">${escapeHTML(d.Address)}</span><div class="cell-sub">${escapeHTML(d.Type)}</div></td><td>${badge(d,s)}<div class="cell-sub">${x.Polling?'采集中…':s?new Date(s.Time).toLocaleTimeString('zh-CN',{hour12:false}):'等待首次采集'}</div></td><td><span class="mono">${value(s?.Rtt,' ms')}</span><div class="cell-sub">无响应 ${value(s?.Loss,'%',0)}</div></td><td><div class="traffic-cell"><span class="in">↙ ${rate(s?.InBps)}</span><span class="out">↗ ${rate(s?.OutBps)}</span></div><div class="cell-sub">${s?.PortCount||0} 个接口</div></td><td><div class="metric-pair"><span class="in">CPU 当前 ${value(s?.Cpu,'%')}</span><span class="out">1分 ${value(s?.Cpu1Min,'%')} · 5分 ${value(s?.Cpu5Min,'%')}</span><span>内存 ${value(s?.Memory,'%')}</span></div><div class="cell-sub">${escapeHTML(s?.MetricEntity||'自动探测')} · ${escapeHTML(s?.MemorySource||'')} · ${escapeHTML(s?.Cpu5MinSource||'')} · ${shortTime(s?.CpuTime||s?.MemoryTime||s?.Time)}</div></td><td><span class="mono">${value(s?.MaxUtilization,'%',1)}</span><div class="cell-sub">最高端口利用率</div></td><td><button class="link-button" data-action="detail" data-id="${d.Id}">详情</button>${d.Demo?'':`<button class="link-button" data-action="edit" data-id="${d.Id}">编辑</button>`}<button class="link-button delete" data-action="delete" data-id="${d.Id}">移除</button></td></tr>`;}).join('');
 let content=`<section class="panel"><div class="panel-head"><h2>设备列表<span class="count">${devices.length}</span></h2><small>每台独立轮询 · 页面每 5 秒刷新</small></div><div class="table-wrap"><table><thead><tr><th>设备名称 / 位置</th><th>管理 IP / 类型</th><th>采集状态</th><th>ICMP 延迟</th><th>实时端口流量</th><th>CPU / 内存</th><th>带宽利用率</th><th>操作</th></tr></thead><tbody>${rows}</tbody></table>${devices.length?'':'<div class="quiet-empty">没有符合条件的设备</div>'}</div></section>`;
 if(view==='overview'){
  let online=state.Devices.filter(x=>x.Current?.Status==='online').length,up=state.Devices.reduce((n,x)=>n+(x.Current?.UpPorts||0),0),all=state.Devices.reduce((n,x)=>n+(x.Current?.PortCount||0),0);
  content+=`<div class="two-col"><section class="panel"><div class="panel-head"><h2>运行概况</h2><small>最近一次采集结果</small></div><div class="device-summary"><div class="summary-row"><span>SNMP 响应设备</span><strong>${online} / ${state.Devices.length}</strong></div><div class="summary-row"><span>端口 UP / 已发现端口</span><strong>${up} / ${all}</strong></div><div class="summary-row"><span>已确认且未恢复的告警</span><strong>${state.Alerts.filter(a=>a.Acknowledged&&!a.Resolved).length}</strong></div><div class="summary-row"><span>采集方式</span><strong>SNMP v2c + 3 次 ICMP 探测</strong></div><div class="summary-row"><span>流量趋势</span><strong>点击设备“详情”查看 24 小时历史</strong></div></div></section>${alertsPanel(state.Alerts.filter(a=>!a.Resolved).slice(0,3),true)}</div>`;
 }
 $('#content').innerHTML=content;
}
function renderTopology(){
 if(!state.Devices.length){$('#content').innerHTML='<section class="panel empty"><div class="empty-orbit">⌘</div><h2>暂时没有拓扑节点</h2><p>请先添加交换机、路由器或防火墙，设备会自动出现在这里。</p><button class="button primary" data-action="add">＋ 添加设备</button></section>';return;}
 const nodes=state.Devices.map((x,i)=>{const d=x.Config,s=x.Current;const angle=(Math.PI*2*i/state.Devices.length)-Math.PI/2;const left=50+38*Math.cos(angle),top=50+38*Math.sin(angle);return `<button class="topology-node" data-action="detail" data-id="${d.Id}" style="left:${left}%;top:${top}%"><span class="node-status ${status(d,s)}"></span><strong>${escapeHTML(d.Name)}</strong><small>${escapeHTML(d.Type)} · ${escapeHTML(d.Address)}</small><span class="node-metrics">CPU ${value(s?.Cpu,'%')} · 1分 ${value(s?.Cpu1Min,'%')} · 5分 ${value(s?.Cpu5Min,'%')}</span><span class="node-metrics">内存 ${value(s?.Memory,'%')} · ${shortTime(s?.MemoryTime||s?.Time)}</span><span>${badge(d,s)}</span></button>`;}).join('');
 const lines=state.Devices.map((x,i)=>{const angle=(Math.PI*2*i/state.Devices.length)-Math.PI/2;const x2=50+38*Math.cos(angle),y2=50+38*Math.sin(angle);return `<line class="topology-link" x1="50%" y1="50%" x2="${x2}%" y2="${y2}%"></line>`;}).join('');
 $('#content').innerHTML=`<section class="panel topology-panel"><div class="panel-head"><h2>网络拓扑展示<span class="count">${state.Devices.length}</span></h2><small>点击节点查看设备详情</small></div><div class="topology-canvas"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">${lines}</svg><div class="topology-core"><strong>NetWatch</strong><small>本机采集服务</small></div>${nodes}</div><div class="topology-legend"><span><i class="legend-dot online"></i>在线</span><span><i class="legend-dot degraded"></i>SNMP 异常</span><span><i class="legend-dot offline"></i>未响应</span><span>当前为设备清单展示，尚未自动发现 LLDP/CDP 物理链路。</span></div></section>`;
}
function chart(history){
 const h=history.filter(x=>x.Time>Date.now()-86400000),max=Math.max(1000,...h.map(x=>Math.max(x.InBps||0,x.OutBps||0)))*1.18;
 const width=850,height=210,left=66,right=20,top=15,bottom=33,innerW=width-left-right,innerH=height-top-bottom;
 if(h.length<2||!h.some(p=>p.InBps!=null))return '<div class="quiet-empty">至少需要两次成功采集才能计算流量。历史保留最近 24 小时。</div>';
 const start=h[0].Time,end=h[h.length-1].Time,span=Math.max(1,end-start);
 const x=p=>left+(p.Time-start)/span*innerW,y=n=>top+innerH-(n/max)*innerH;
 const path=key=>{let result='',previous=null;for(const p of h){if(p[key]==null){previous=null;continue;}const gap=previous&&p.Time-previous.Time>Math.max(180000,(span/Math.max(1,h.length-1))*3);result+=(previous&&!gap?' L ':' M ')+x(p).toFixed(1)+' '+y(p[key]).toFixed(1);previous=p;}return result;};
 let grid='';for(let i=0;i<=4;i++){let yp=top+innerH*i/4;grid+=`<line class="chart-grid" x1="${left}" y1="${yp}" x2="${width-right}" y2="${yp}"/><text class="chart-label" text-anchor="end" x="${left-10}" y="${yp+3}">${rate(max*(1-i/4))}</text>`;}
 for(let i=0;i<=4;i++){let t=start+span*i/4;grid+=`<text class="chart-label" text-anchor="middle" x="${left+innerW*i/4}" y="${height-8}">${new Date(t).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false})}</text>`;}
 return `<div class="chart-container"><svg viewBox="0 0 ${width} ${height}" role="img" aria-label="最近 24 小时内设备所有端口进出流量趋势，横轴为时间，纵轴为每秒比特数"><title>端口流量趋势</title>${grid}<path class="line-in" d="${path('InBps')}"/><path class="line-out" d="${path('OutBps')}"/></svg></div><div class="chart-note">展示 ${h.length} 次采样 · 缺失采样保持断线 · 可导出 CSV 查看原始数据</div>`;
}
function renderDetail(){let d=detail.Config,s=detail.Current,h=detail.History;let content=`<button class="link-button back" data-action="back">← 返回设备列表</button><div class="detail-heading"><div><h2>${escapeHTML(d.Name)} ${d.Demo?'<span class="badge demo">演示数据</span>':''}</h2><p>${escapeHTML(d.Address)} · ${escapeHTML(d.Type)} · ${escapeHTML(d.Location||'未设置位置')}</p></div><div class="heading-actions">${badge(d,s)}<button class="button" data-action="export" data-id="${d.Id}">导出历史 CSV</button>${d.Demo?'':`<button class="button" data-action="edit" data-id="${d.Id}">编辑设备</button>`}</div></div>`;
 if(s?.Error)content+=`<div class="notice">${escapeHTML(s.Error)}</div>`;
 if(!s){$('#content').innerHTML=content+'<section class="panel quiet-empty">等待首次采集，请稍后刷新。</section>';return;}
 content+=`<section class="panel"><div class="detail-metrics">${[['平均延迟',value(s.Rtt,' ms')],['ICMP 探测无响应',value(s.Loss,'%',0)],['CPU 当前',s.Cpu==null?'无数据':value(s.Cpu,'%')],['CPU 1 分钟',s.Cpu1Min==null?'无数据':value(s.Cpu1Min,'%')],['CPU 5 分钟',s.Cpu5Min==null?'无数据':value(s.Cpu5Min,'%')],['内存当前',s.Memory==null?'无数据':value(s.Memory,'%')],['设备运行时间',uptime(s.UptimeTicks)]].map(([k,v])=>`<div class="detail-metric"><small>${k}</small><strong>${v}</strong></div>`).join('')}</div><div class="detail-description">${escapeHTML(s.Description||'设备描述暂不可用')}<br>系统名称：${escapeHTML(s.SysName||'—')} · 指标实体：${escapeHTML(s.MetricEntity||'自动探测')} · 内存来源：${escapeHTML(s.MemorySource||'—')} · 5 分钟来源：${escapeHTML(s.Cpu5MinSource||'—')} · CPU/内存采集：${time(s.CpuTime||s.Time)} / ${time(s.MemoryTime||s.Time)} · 平台窗口样本：${s.Cpu5MinSamples||0}</div></section>`;
 content+=`<section class="panel"><div class="panel-head"><h2>端口流量趋势 <span class="count">最近 24 小时</span></h2><div class="legend"><span><i></i>入方向</span><span><i class="orange"></i>出方向</span></div></div>${chart(h)}<div class="section-note">合计为该设备所有接口之和；交换转发、VLAN、聚合口可能重复统计，不等于出口带宽用量。</div></section>`;
 const ports=[...s.Interfaces].sort((a,b)=>(b.InBps||0)+(b.OutBps||0)-(a.InBps||0)-(a.OutBps||0));
 content+=`<section class="panel"><div class="panel-head"><h2>接口状态<span class="count">${ports.length}</span></h2><small>按进出流量降序 · 错误/丢弃为设备累计计数</small></div><div class="table-wrap"><table><thead><tr><th>接口 / 描述</th><th>管理 / 链路</th><th>协商速率</th><th>入方向</th><th>出方向</th><th>利用率</th><th>错误 入 / 出</th><th>丢弃 入 / 出</th><th>计数器</th></tr></thead><tbody>${ports.map(p=>`<tr><td><strong>${escapeHTML(p.Name)}</strong><div class="cell-sub">${escapeHTML(p.Alias||'ifIndex '+p.Index)}</div></td><td><span class="badge ${p.Oper===1?'online':p.Admin===2?'paused':'warning'}">${p.Admin===1?'启用':'禁用/未知'} / ${({1:'UP',2:'DOWN',3:'TEST',4:'未知',5:'DORMANT',6:'不存在',7:'下层 DOWN'})[p.Oper]||'未知'}</span></td><td class="mono">${p.Speed?rate(p.Speed):'未知'}</td><td class="mono in">${rate(p.InBps)}</td><td class="mono out">${rate(p.OutBps)}</td><td class="mono">${value(p.Utilization,'%')}</td><td class="mono">${p.InErrors??'—'} / ${p.OutErrors??'—'}</td><td class="mono">${p.InDiscards??'—'} / ${p.OutDiscards??'—'}</td><td class="mono">${p.Counter64?'64 位':'32 位'}</td></tr>`).join('')}</tbody></table>${ports.length?'':'<div class="quiet-empty">尚无接口数据</div>'}</div><div class="section-note">“—”表示未支持、尚无第二次采样或计数器重置。利用率取入/出方向较高值 ÷ 接口速率。ICMP 无响应也可能由设备禁 Ping 导致。</div></section>`;
 $('#content').innerHTML=content;
}
function alertsPanel(alerts,compact){return `<section class="panel"><div class="panel-head"><h2>${compact?'当前告警':'告警记录'}<span class="count">${alerts.length}</span></h2><small>${compact?'状态变化自动更新':'最近 250 条 · 确认不等于恢复'}</small></div>${alerts.length?'<div class="alert-list">'+alerts.map(a=>`<article class="alert-item"><div class="alert-mark ${a.Level}">${a.Resolved?'✓':'!'}</div><div class="alert-content"><h3>${escapeHTML(a.Message)}</h3><p>${escapeHTML(a.DeviceName)} · <span class="badge ${a.Resolved?'recovered':a.Level}">${a.Resolved?'已恢复':a.Level==='critical'?'严重':a.Level==='info'?'事件':'警告'}</span> ${a.Acknowledged?'已确认':''}</p><time>${time(a.Time)}${a.Resolved?' · 恢复于 '+time(a.Resolved):''}</time></div>${!a.Acknowledged?`<button class="link-button" data-action="ack" data-id="${a.Id}">确认</button>`:''}</article>`).join('')+'</div>':'<div class="quiet-empty">暂无告警记录，设备状态变化将在这里显示。</div>'}</section>`;}
function renderGuide(){$('#content').innerHTML=`<div class="guide-grid"><section class="panel guide"><h2>01 / 接入网络设备</h2><ol><li>在交换机、路由器或防火墙上启用 <b>SNMP v2c</b>，创建只读社区字符串。</li><li>在设备的 SNMP ACL 中允许这台 Windows 电脑的管理 IP 访问。默认端口为 <b>UDP 161</b>。</li><li>点击“添加设备”，填写管理 IP、社区字符串和轮询间隔。</li><li>首次采集显示端口信息，第二次成功采集开始显示流量。常用间隔为 60 秒。</li></ol><p>只需要设备提供 SNMP 服务，Windows 本机无需安装 SNMP 服务。SNMP v2c 的社区字符串在线路上不加密，适合受控管理网络。</p><button class="button primary" data-action="add">添加设备</button> <button class="button" data-action="demo">载入演示设备</button></section><section class="panel guide"><h2>02 / 常见采集问题</h2><ul><li><b>Ping 正常，SNMP 异常：</b>检查社区字符串、版本、UDP 端口及设备只读视图权限。</li><li><b>两者均无响应：</b>检查地址、路由和 ACL，不能仅凭探测失败断定设备断电。</li><li><b>端口有状态但没有流量：</b>等待第二次采集。高速端口需支持 IF-MIB 的 64 位 ifHCInOctets / ifHCOutOctets。</li><li><b>CPU / 内存为空：</b>确认 SNMP 只读视图允许 HOST-RESOURCES-MIB、H3C ENTITY-EXT-MIB、华为 HUAWEI-ENTITY-EXTENT-MIB 或 ENTITY-MIB；内存优先使用系统 RAM 比例，不需要 OID。</li><li><b>CPU 数值与命令行不同：</b>H3C 或华为设备会优先读取主控实体的 SNMP 指标；设备不提供原生 5 分钟项时，才显示本程序按近 5 分钟采样计算的均值。页面会标明数据来源。</li><li><b>流量合计比出口大：</b>接口汇总会重复计入设备内部转发、VLAN 或聚合口，请以对应物理端口为准。</li></ul></section><section class="panel guide guide-wide"><h2>03 / 指标与告警</h2><div class="table-wrap"><table><thead><tr><th>指标</th><th>采集与计算</th><th>告警条件</th></tr></thead><tbody><tr><td>设备状态 / 延迟</td><td>SNMP 响应 + 每轮 3 次 ICMP；延迟为成功响应平均值</td><td>连续 3 次 SNMP 失败；下一次成功后恢复</td></tr><tr><td>端口进出流量</td><td>计数器差值 × 8 / 两次实际采集时间差</td><td>利用率达到设备设置的阈值；低于阈值 5 个百分点后恢复</td></tr><tr><td>端口状态</td><td>ifAdminStatus / ifOperStatus</td><td>已观察到 UP 的启用端口变为非 UP；重新 UP 或管理关闭后恢复</td></tr><tr><td>错误包 / 丢弃包</td><td>接口累计计数；根据相邻采样判断是否增加</td><td>计数增加触发；下一轮没有增加后恢复</td></tr><tr><td>CPU / 内存</td><td>自动识别 H3C/华为主控实体并读取可用的当前/1 分钟/5 分钟值，或使用标准 HOST-RESOURCES-MIB；无原生 5 分钟项时使用平台采样均值</td><td>达到同一百分比阈值；带 5 个百分点恢复滞回</td></tr></tbody></table></div></section><section class="panel guide guide-wide"><h2>04 / 运行与数据</h2><p>关闭浏览器后仍继续采集。退出采集程序：右键 Windows 托盘 NetWatch 图标 → “退出并停止监测”。电脑需要保持开机，睡眠时无法采集。程序默认不会设置开机自启。</p><p>数据目录：<code>${escapeHTML(state.DataDirectory)}</code>。社区字符串按当前 Windows 用户加密。若更换电脑或 Windows 用户，请重新填写社区字符串。</p><p>历史保留最近 24 小时（每设备最多 2880 点），告警最多 2000 条；支持最多 100 台设备、每台最多 512 个接口，4 台并发采集。移除设备会停止监测，磁盘中的历史文件保留供备份。</p><p>此版本提供本机 Web 管理、SNMP v2c 轮询与界面告警；不包含 SSH 命令采集、SNMP v3、Trap/Syslog 接收、邮件/短信通知、Windows 服务安装或多人远程登录。</p></section></div>`;}
function openForm(id){let form=$('#deviceForm');form.reset();form.elements.Id.value='';$('#formError').textContent='';const d=id?state.Devices.find(x=>x.Config.Id===id)?.Config:null;$('#dialogTitle').textContent=d?'编辑网络设备':'添加网络设备';if(d){for(const k of ['Id','Name','Address','Type','Location','Port','Interval','Timeout','Threshold'])form.elements[k].value=d[k]??'';form.elements.Enabled.checked=d.Enabled;}form.elements.Community.required=!d;$('#communityHelp').textContent=d?'留空保留已保存的社区字符串；保存后会重新建立流量基线。':'在设备侧开启 SNMP v2c，并允许本机管理 IP 读取。';$('#deviceDialog').showModal();}
document.addEventListener('click',async event=>{const target=event.target.closest('[data-action],[data-view],[data-filter]');if(!target)return;if(target.tagName==='A')event.preventDefault();if(target.dataset.view){view=target.dataset.view;selected=null;detail=null;if(view==='devices')devicePage=1;render();return;}if(target.dataset.filter){filter=target.dataset.filter;devicePage=1;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('selected',x===target));render();return;}const action=target.dataset.action,id=target.dataset.id;try{switch(action){case 'add':openForm();break;case 'edit':openForm(id);break;case 'close-dialog':$('#deviceDialog').close();break;case 'back':selected=null;detail=null;render();break;case 'detail':selected=id;detail=await api('device?id='+encodeURIComponent(id));render();window.scrollTo(0,0);break;case 'device-page':devicePage=Math.max(1,Number(target.dataset.page)||1);render();window.scrollTo({top:document.querySelector('#content')?.offsetTop||0,behavior:'smooth'});break;case 'poll':target.disabled=true;await api('poll',{Id:selected});toast('已加入采集队列');await refresh();break;case 'demo':await api('demo',{});toast('已添加 3 台模拟设备');view='overview';await refresh();break;case 'delete':{const d=state.Devices.find(x=>x.Config.Id===id)?.Config;if(!confirm('从平台移除“'+(d?.Name||'设备')+'”并停止采集？设备配置本身不会改变，已保存的历史文件将保留。'))return;await api('delete',{Id:id});if(selected===id){selected=null;detail=null;}toast('设备已移除');await refresh();break;}case 'ack':await api('ack',{Id:id});await refresh();break;case 'export':{const r=await fetch('/api/export?id='+encodeURIComponent(id),{headers:{'X-NetWatch-Token':token}});if(!r.ok)throw Error('导出失败');const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='NetWatch-'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('历史数据已导出');break;}}}catch(e){toast(e.message);}finally{target.disabled=false;}});
$('#deviceForm').addEventListener('submit',async e=>{e.preventDefault();let form=e.currentTarget;const data=Object.fromEntries(new FormData(form));data.Enabled=form.elements.Enabled.checked;$('#saveButton').disabled=true;$('#formError').textContent='';try{await api('save',data);$('#deviceDialog').close();toast('设备已保存，等待采集');await refresh();}catch(err){$('#formError').textContent=err.message;}finally{$('#saveButton').disabled=false;}});
$('#search').addEventListener('input',()=>{devicePage=1;render();});$('#typeFilter').addEventListener('change',()=>{devicePage=1;render();});
setInterval(()=>{$('#clock').textContent=new Date().toLocaleString('zh-CN',{hour12:false});},1000);
(async()=>{updateMetricHelp();try{const r=await fetch('/api/session');if(!r.ok)throw Error('服务不可用');const session=await r.json();token=session.Token;const address=$('#serverAddress');if(address)address.textContent=session.AccessUrl||location.host;await refresh();setInterval(refresh,5000);}catch(e){$('#connection').textContent='连接失败';$('#connection').classList.add('bad');toast(e.message);}})();

/* Dashboard polish, stable name ordering and persisted topology layout. */
const deviceCollator=new Intl.Collator('zh-CN',{numeric:true,sensitivity:'base'});
const topologyStorageKey='netwatch.topology.positions.v1';
let topologyPositions={};let topologyDrag=null;let suppressTopologyClick=false;
try{topologyPositions=JSON.parse(localStorage.getItem(topologyStorageKey)||'{}')||{};}catch{topologyPositions={};}
function sortedDevices(list=state.Devices){return [...list].sort((a,b)=>deviceCollator.compare(String(a.Config?.Name||''),String(b.Config?.Name||''))||deviceCollator.compare(String(a.Config?.Address||''),String(b.Config?.Address||'')));}
function metricAverage(key,list=state.Devices){const values=list.map(x=>x.Current?.[key]).filter(v=>Number.isFinite(Number(v))).map(Number);return values.length?values.reduce((a,b)=>a+b,0)/values.length:null;}
function metricNumber(value){return Number.isFinite(Number(value))?Math.max(0,Math.min(100,Number(value))):null;}
function gaugeCard(label,valueText,raw,detail,accent,icon){const n=metricNumber(raw),ring=n==null?0:n;return `<article class="gauge-card"><div class="gauge-ring" style="--gauge:${ring};--gauge-color:${accent}"><div class="gauge-center"><strong>${valueText}</strong><small>当前</small></div></div><div class="gauge-copy"><span class="gauge-icon">${icon}</span><div><h3>${label}</h3><p>${escapeHTML(detail)}</p></div></div></article>`;}
function miniLineChart(points,series,empty='积累两次采样后显示趋势'){const valid=(points||[]).filter(p=>series.some(s=>Number.isFinite(Number(p[s.key]))));if(valid.length<2)return `<div class="mini-empty">${empty}</div>`;const w=520,h=142,pad={l:38,r:12,t:12,b:24},values=valid.flatMap(p=>series.map(s=>Number(p[s.key])).filter(Number.isFinite)),max=Math.max(1,...values)*1.12,min=Math.min(0,...values),span=Math.max(1,max-min),x=i=>pad.l+i*(w-pad.l-pad.r)/Math.max(1,valid.length-1),y=v=>pad.t+(max-v)/span*(h-pad.t-pad.b),path=key=>{let d='',started=false;valid.forEach((p,i)=>{const v=Number(p[key]);if(!Number.isFinite(v)){started=false;return;}d+=(started?' L ':' M ')+x(i).toFixed(1)+' '+y(v).toFixed(1);started=true;});return d;};let grid='';for(let i=0;i<4;i++){const gy=pad.t+i*(h-pad.t-pad.b)/3;grid+=`<line x1="${pad.l}" y1="${gy}" x2="${w-pad.r}" y2="${gy}"/>`;};const labels=[0,Math.floor((valid.length-1)/2),valid.length-1].map(i=>`<text x="${x(i)}" y="${h-5}" text-anchor="middle">${new Date(valid[i].Time).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false})}</text>`).join('');return `<div class="mini-chart"><svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><g class="mini-grid">${grid}</g>${series.map(s=>`<path class="${s.className}" d="${path(s.key)}"/>`).join('')}<g class="mini-labels">${labels}</g></svg><div class="mini-legend">${series.map(s=>`<span><i class="${s.className}"></i>${s.label}</span>`).join('')}</div></div>`;}
function typeDistribution(devices){const order=['交换机','路由器','防火墙','其他'],colors=['#24d9e8','#6ba9ff','#ff6e89','#ffbf69'],counts=order.map(type=>devices.filter(x=>x.Config.Type===type).length),total=Math.max(1,devices.length);let cursor=0;const stops=counts.map((count,i)=>{const start=cursor;cursor+=count/total*100;return `${colors[i]} ${start}% ${cursor}%`;}).join(',');return `<div class="type-distribution"><div class="type-donut" style="background:conic-gradient(${stops||'#17354a 0 100%'})"><div><strong>${devices.length}</strong><small>设备总数</small></div></div><div class="type-list">${order.map((type,i)=>`<span><i style="background:${colors[i]}"></i>${type}<b>${counts[i]}</b><em>${devices.length?(counts[i]/devices.length*100).toFixed(1):'0.0'}%</em></span>`).join('')}</div></div>`;}
function dashboardTopology(devices){const list=sortedDevices(devices).slice(0,18),groups=[list.filter(x=>x.Config.Type==='防火墙'),list.filter(x=>x.Config.Type==='路由器'),list.filter(x=>x.Config.Type==='交换机'),list.filter(x=>!['防火墙','路由器','交换机'].includes(x.Config.Type))].filter(x=>x.length),ys=groups.length===1?[53]:groups.length===2?[35,70]:groups.length===3?[23,50,78]:[16,38,62,84],positions=[];groups.forEach((group,row)=>group.forEach((x,i)=>positions.push({x,y:ys[row],left:group.length===1?50:10+i*80/(group.length-1)})));const nodes=positions.map(({x,left,y})=>{const d=x.Config,s=x.Current;return `<button class="noc-node" data-action="detail" data-id="${d.Id}" style="left:${left}%;top:${y}%"><span class="noc-device-icon">${d.Type==='防火墙'?'◇':d.Type==='路由器'?'⌁':'▤'}</span><i class="${status(d,s)}"></i><strong>${escapeHTML(d.Name)}</strong><small>${escapeHTML(d.Address)}</small></button>`;}).join(''),lines=positions.map(({left,y})=>`<line x1="50%" y1="49%" x2="${left}%" y2="${y}%"/>`).join('');return `<div class="noc-map"><svg viewBox="0 0 100 100" preserveAspectRatio="none">${lines}</svg><div class="noc-core"><span></span><strong>Internet</strong><small>NETWORK CORE</small></div>${nodes}${devices.length>18?`<span class="topology-more">另有 ${devices.length-18} 台设备</span>`:''}</div>`;}
function overviewAlerts(){const items=state.Alerts.filter(a=>!a.Resolved).slice(0,5);return items.length?items.map(a=>`<div class="noc-alert"><span class="alert-level ${a.Level}">${a.Level==='critical'?'紧急':a.Level==='info'?'提示':'警告'}</span><div><strong>${escapeHTML(a.DeviceName)}</strong><small>${escapeHTML(a.Message)}</small></div><time>${shortTime(a.Time)}</time></div>`).join(''):'<div class="mini-empty">当前没有未恢复告警</div>';}
function overviewLinks(){const rows=(state.Links||[]).slice(0,6);return rows.length?`<div class="link-table"><div class="link-head"><span>设备 / 接口</span><span>状态</span><span>速率</span><span>流量</span><span>利用率</span></div>${rows.map(p=>`<div class="link-row"><span><b>${escapeHTML(p.DeviceName)}</b><small>${escapeHTML(p.Interface)} · ${escapeHTML(p.Address)}</small></span><span class="link-state ${p.Oper===1?'up':'down'}">${p.Oper===1?'运行':'非 UP'}</span><span>${p.Speed?rate(p.Speed):'未知'}</span><span>${rate((p.InBps||0)+(p.OutBps||0))}</span><span>${value(p.Utilization,'%',1)}</span></div>`).join('')}</div>`:'<div class="mini-empty">采集到接口后显示链路状态</div>';}
function overviewEvents(){const alerts=state.Alerts.slice(0,5),samples=sortedDevices().filter(x=>x.Current).sort((a,b)=>b.Current.Time-a.Current.Time).slice(0,Math.max(0,5-alerts.length)).map(x=>({Time:x.Current.Time,Level:x.Current.Snmp?'info':'warning',DeviceName:x.Config.Name,Message:x.Current.Snmp?'采集完成':'采集未成功'})),events=[...alerts.map(a=>({Time:a.Time,Level:a.Level,DeviceName:a.DeviceName,Message:a.Message})),...samples].sort((a,b)=>b.Time-a.Time).slice(0,5);return events.length?events.map(e=>`<div class="event-row"><time>${shortTime(e.Time)}</time><b class="${e.Level}">${String(e.Level).toUpperCase()}</b><span>${escapeHTML(e.DeviceName)}</span><small>${escapeHTML(e.Message)}</small></div>`).join(''):'<div class="mini-empty">暂无采集事件</div>';}
function deviceRowHTML(x){let d=x.Config,s=x.Current;return `<tr><td><div class="device-title"><span class="device-icon">${d.Type==='交换机'?'▤':d.Type==='路由器'?'⌁':'◇'}</span><div><a href="#device-${d.Id}" data-action="detail" data-id="${d.Id}" class="device-name">${escapeHTML(d.Name)}</a><div class="cell-sub">${escapeHTML(d.Location||'未设置位置')}${d.Demo?'<span class="badge demo">演示</span>':''}</div></div></div></td><td><span class="mono">${escapeHTML(d.Address)}</span><div class="cell-sub">${escapeHTML(d.Type)}</div></td><td>${badge(d,s)}<div class="cell-sub">${x.Polling?'采集中…':s?shortTime(s.Time):'等待首次采集'}</div></td><td><span class="mono">${value(s?.Rtt,' ms')}</span><div class="cell-sub">无响应 ${value(s?.Loss,'%',0)}</div></td><td><div class="traffic-cell"><span class="in">↙ ${rate(s?.InBps)}</span><span class="out">↗ ${rate(s?.OutBps)}</span></div><div class="cell-sub">${s?.PortCount||0} 个接口</div></td><td><div class="metric-pair"><span class="in">CPU 当前 ${value(s?.Cpu,'%')}</span><span class="out">1分 ${value(s?.Cpu1Min,'%')} · 5分 ${value(s?.Cpu5Min,'%')}</span><span>内存 ${value(s?.Memory,'%')}</span></div><div class="cell-sub">${escapeHTML(s?.MetricEntity||'自动探测')} · ${escapeHTML(s?.MemorySource||'')} · ${shortTime(s?.CpuTime||s?.MemoryTime||s?.Time)}</div></td><td><span class="mono">${value(s?.MaxUtilization,'%',1)}</span><div class="cell-sub">最高端口利用率</div></td><td><button class="link-button" data-action="detail" data-id="${d.Id}">详情</button>${d.Demo?'':`<button class="link-button" data-action="edit" data-id="${d.Id}">编辑</button>`}<button class="link-button delete" data-action="delete" data-id="${d.Id}">移除</button></td></tr>`;}
function deviceTable(devices,title='设备列表',compact=false){const rows=devices.map(deviceRowHTML).join('');return `<section class="panel ${compact?'snapshot-panel':''}"><div class="panel-head"><div><span class="panel-kicker">${compact?'LIVE INVENTORY':'DEVICE INVENTORY'}</span><h2>${title}<span class="count">${devices.length}</span></h2></div><small>${compact?'按设备名称排序 · 实时快照':'按设备名称排序 · 每台独立轮询 · 页面每 5 秒刷新'}</small></div><div class="table-wrap"><table class="${compact?'snapshot-table':''}"><thead><tr><th>设备名称 / 位置</th><th>管理 IP / 类型</th><th>采集状态</th><th>ICMP 延迟</th><th>实时端口流量</th><th>CPU / 内存</th><th>带宽利用率</th><th>操作</th></tr></thead><tbody>${rows}</tbody></table>${devices.length?'':'<div class="quiet-empty">没有符合条件的设备</div>'}</div></section>`;}
function renderStats(){const online=state.Devices.filter(x=>status(x.Config,x.Current)==='online').length,problems=state.Devices.filter(x=>['offline','degraded'].includes(status(x.Config,x.Current))).length,measured=state.Devices.filter(x=>x.Config.Enabled&&x.Current?.Snmp&&x.Current.InBps!=null),total=measured.length?measured.reduce((a,x)=>a+x.Current.InBps,0):null;$('#stats').innerHTML=[['设备总数',state.Devices.length,'台','交换机 / 路由器 / 防火墙','◫','stat-cyan'],['正常在线',online,'台',problems?`${problems} 台设备需要关注`:'SNMP 状态稳定','✓','stat-green'],['端口入方向合计',rate(total),'','已采集接口求和，可能重复计流','↙','stat-blue'],['未恢复告警',state.ActiveAlerts,'条','确认不会改变恢复状态','♧',state.ActiveAlerts?'stat-red':'stat-amber']].map(([label,n,unit,foot,icon,kind])=>`<article class="stat ${kind}"><div class="stat-top"><span>${label}</span><span class="stat-icon">${icon}</span></div><div class="stat-value">${n}<small>${unit}</small></div><div class="stat-foot">${foot}</div><span class="stat-scan"></span></article>`).join('');}
function renderOverview(){const devices=state.Devices,total=devices.length,online=devices.filter(x=>status(x.Config,x.Current)==='online').length,offline=devices.filter(x=>status(x.Config,x.Current)==='offline').length,degraded=devices.filter(x=>status(x.Config,x.Current)==='degraded').length,enabled=devices.filter(x=>x.Config.Enabled).length,availability=enabled?online/enabled*100:null,rtt=metricAverage('Rtt'),loss=metricAverage('Loss'),util=metricAverage('MaxUtilization'),cpu=metricAverage('Cpu'),memory=metricAverage('Memory'),traffic=sortedDevices().map(x=>({x,total:(x.Current?.InBps||0)+(x.Current?.OutBps||0)})).sort((a,b)=>b.total-a.total),maxTraffic=Math.max(1,...traffic.map(x=>x.total)),upPorts=devices.reduce((n,x)=>n+(x.Current?.UpPorts||0),0),ports=devices.reduce((n,x)=>n+(x.Current?.PortCount||0),0),topRows=traffic.slice(0,5).map(({x,total:load},i)=>`<div class="rank-row"><b>${i+1}</b><span><strong>${escapeHTML(x.Config.Name)}</strong><small>${escapeHTML(x.Config.Address)}</small></span><div><i style="width:${load/maxTraffic*100}%"></i></div><em>${rate(load)}</em></div>`).join('')||'<div class="mini-empty">暂无流量数据</div>',statusTotal=Math.max(1,total),trend=state.Trend||[];
 const quality=[['网络可用性',availability==null?'—':value(availability,'%'),availability,'#55e6c1','◉'],['平均时延',rtt==null?'—':value(rtt,' ms'),Math.min(100,rtt||0),'#a478ff','◷'],['探测无响应',loss==null?'—':value(loss,'%'),loss,'#44bfff','⌁'],['端口利用率',util==null?'—':value(util,'%'),util,'#ffbf69','↗']].map(([label,text,n,color,icon])=>`<article class="quality-card" style="--quality:${Number(n)||0};--quality-color:${color}"><span>${icon}</span><div><small>${label}</small><strong>${text}</strong></div></article>`).join('');
 $('#content').innerHTML=`<section class="noc-dashboard"><section class="noc-left"><section class="panel noc-panel device-overview"><div class="noc-title"><span>◉</span><h2>设备总览</h2></div><div class="overview-rings"><div class="overview-ring cyan" style="--p:100"><strong>${total}</strong><small>设备总数</small></div><div class="overview-ring green" style="--p:${total?online/total*100:0}"><strong>${online}</strong><small>在线设备</small></div><div class="overview-ring red" style="--p:${total?offline/total*100:0}"><strong>${offline}</strong><small>离线设备</small></div></div></section><section class="panel noc-panel"><div class="noc-title"><span>◫</span><h2>设备类型分布</h2></div>${typeDistribution(devices)}</section><section class="panel noc-panel"><div class="noc-title"><span>↗</span><h2>全网流量趋势</h2></div>${miniLineChart(trend,[{key:'InBps',label:'上行流量',className:'line-cyan'},{key:'OutBps',label:'下行流量',className:'line-green'}])}</section><section class="panel noc-panel"><div class="noc-title"><span>▤</span><h2>TOP 5 设备流量排行</h2></div><div class="rank-list">${topRows}</div></section></section><section class="noc-center"><div class="quality-grid">${quality}</div><section class="panel noc-panel noc-topology"><div class="noc-title"><span>⌘</span><h2>全网态势拓扑</h2><button data-view="topology">完整拓扑</button></div>${dashboardTopology(devices)}</section><section class="panel noc-panel link-status"><div class="noc-title"><span>◎</span><h2>链路状态</h2><small>当前采样 · 按利用率排列</small></div>${overviewLinks()}</section></section><section class="noc-right"><section class="panel noc-panel"><div class="noc-title"><span>♧</span><h2>实时告警</h2><b>${state.ActiveAlerts} 条未处理</b></div><div class="noc-alerts">${overviewAlerts()}</div></section><section class="panel noc-panel"><div class="noc-title"><span>◔</span><h2>设备状态概览</h2></div><div class="status-overview"><div class="status-donut" style="background:conic-gradient(#55e6c1 0 ${online/statusTotal*100}%,#ffbf69 ${online/statusTotal*100}% ${(online+degraded)/statusTotal*100}%,#ff6e89 ${(online+degraded)/statusTotal*100}% 100%)"><strong>${total}</strong><small>设备总数</small></div><div><span><i class="green"></i>正常<b>${online}</b><em>${(online/statusTotal*100).toFixed(1)}%</em></span><span><i class="amber"></i>异常<b>${degraded}</b><em>${(degraded/statusTotal*100).toFixed(1)}%</em></span><span><i class="red"></i>离线<b>${offline}</b><em>${(offline/statusTotal*100).toFixed(1)}%</em></span></div></div></section><section class="panel noc-panel"><div class="noc-title"><span>◫</span><h2>CPU / 内存趋势</h2><small>跨设备平均值</small></div>${miniLineChart(trend,[{key:'Cpu',label:'CPU',className:'line-purple'},{key:'Memory',label:'内存',className:'line-amber'}])}<div class="current-metrics"><span>CPU 当前 <b>${value(cpu,'%')}</b></span><span>内存当前 <b>${value(memory,'%')}</b></span></div></section><section class="panel noc-panel"><div class="noc-title"><span>▧</span><h2>实时事件</h2></div><div class="event-list">${overviewEvents()}</div></section></section></section>`;}
function filteredDevices(){const q=($('#search')?.value||'').toLowerCase(),kind=$('#typeFilter')?.value||'';return sortedDevices(state.Devices.filter(x=>{const k=status(x.Config,x.Current);return (!kind||x.Config.Type===kind)&&(!q||[x.Config.Name,x.Config.Address,x.Config.Location].join(' ').toLowerCase().includes(q))&&(filter==='all'||(filter==='online'&&k==='online')||(filter==='problem'&&['offline','degraded'].includes(k)));}));}
function pagination(total,totalPages){const pages=[];for(let page=1;page<=totalPages;page++)if(totalPages<=7||page===1||page===totalPages||Math.abs(page-devicePage)<=1)pages.push(`<button class="page-button ${page===devicePage?'active':''}" data-action="device-page" data-page="${page}" ${page===devicePage?'aria-current="page"':''}>${page}</button>`);else if(pages[pages.length-1]!=='<span class="page-ellipsis">…</span>')pages.push('<span class="page-ellipsis">…</span>');return `<nav class="pagination" aria-label="设备分页"><span class="page-summary">共 ${total} 台 · 每页 10 台 · 第 ${devicePage} / ${totalPages} 页</span><div class="page-controls"><button class="page-button wide" data-action="device-page" data-page="${devicePage-1}" ${devicePage===1?'disabled':''}>上一页</button>${pages.join('')}<button class="page-button wide" data-action="device-page" data-page="${devicePage+1}" ${devicePage===totalPages?'disabled':''}>下一页</button></div></nav>`;}
function renderDevices(){if(view==='overview'){renderOverview();return;}if(!state.Devices.length){$('#content').innerHTML=`<section class="panel empty"><div class="empty-orbit">⌁</div><h2>让网络状态变得清晰</h2><p>添加交换机、路由器或防火墙的管理 IP 和只读社区字符串，即可开始查看流量、端口状态与告警。</p><button class="button primary" data-action="add">＋ 添加第一台设备</button> <button class="button" data-action="demo">体验演示数据</button><div class="empty-steps"><span><b>1</b>设备开启 SNMP</span><span><b>2</b>填写连接信息</span><span><b>3</b>自动采集与告警</span></div></section>`;return;}const devices=filteredDevices(),totalPages=Math.max(1,Math.ceil(devices.length/10));devicePage=Math.min(Math.max(1,devicePage),totalPages);const pageDevices=devices.slice((devicePage-1)*10,devicePage*10);$('#content').innerHTML=deviceTable(pageDevices,'设备管理')+pagination(devices.length,totalPages);}
function defaultTopologyPosition(index,total){if(total<=16){const angle=(Math.PI*2*index/Math.max(1,total))-Math.PI/2;return {x:Math.round((50+36*Math.cos(angle))*10)/10,y:Math.round((50+35*Math.sin(angle))*10)/10};}const cols=Math.ceil(Math.sqrt(total*1.75)),rows=Math.ceil(total/cols),col=index%cols,row=Math.floor(index/cols);return {x:cols===1?50:12+col*76/(cols-1),y:rows===1?50:13+row*74/(rows-1)};}
function topologyPosition(id,index,total){const saved=(state.Topology||{})[id]||topologyPositions[id];if(saved&&Number.isFinite(Number(saved.x))&&Number.isFinite(Number(saved.y)))return {x:Math.max(12,Math.min(88,Number(saved.x))),y:Math.max(13,Math.min(87,Number(saved.y)))};return defaultTopologyPosition(index,total);}
function saveTopologyPositions(){try{localStorage.setItem(topologyStorageKey,JSON.stringify(topologyPositions));}catch{}}
function updateTopologyLines(canvas){canvas.querySelectorAll('.topology-link').forEach(line=>{const id=line.dataset.id,node=[...canvas.querySelectorAll('.topology-node')].find(item=>item.dataset.id===id);if(node){line.setAttribute('x2',node.style.left);line.setAttribute('y2',node.style.top);}});}
function renderTopology(){const devices=sortedDevices();if(!devices.length){$('#content').innerHTML='<section class="panel empty"><div class="empty-orbit">⌘</div><h2>暂时没有拓扑节点</h2><p>请先添加交换机、路由器或防火墙，设备会自动出现在这里。</p><button class="button primary" data-action="add">＋ 添加设备</button></section>';return;}const dense=devices.length>16?' dense':'',veryDense=devices.length>40?' very-dense':'',positions=devices.map((x,i)=>topologyPosition(x.Config.Id,i,devices.length)),nodes=devices.map((x,i)=>{const d=x.Config,s=x.Current,p=positions[i];return `<button class="topology-node" data-action="detail" data-id="${d.Id}" data-x="${p.x}" data-y="${p.y}" style="left:${p.x}%;top:${p.y}%" title="拖动节点，单击查看详情"><span class="node-status ${status(d,s)}"></span><strong>${escapeHTML(d.Name)}</strong><small>${escapeHTML(d.Type)} · ${escapeHTML(d.Address)}</small><span class="node-metrics">CPU ${value(s?.Cpu,'%')} · 内存 ${value(s?.Memory,'%')}</span><span>${badge(d,s)}</span></button>`;}).join(''),lines=devices.map((x,i)=>`<line class="topology-link" data-id="${x.Config.Id}" x1="50%" y1="50%" x2="${positions[i].x}%" y2="${positions[i].y}%"></line>`).join('');$('#content').innerHTML=`<section class="panel topology-panel${dense}${veryDense}"><div class="panel-head"><div><span class="panel-kicker">FIT-TO-SCREEN TOPOLOGY</span><h2>网络拓扑展示<span class="count">${devices.length}</span></h2></div><div class="topology-actions"><small>已自动适配当前屏幕 · 可拖动并自动保存</small><button class="button" data-action="reset-topology">自动排列</button></div></div><div class="topology-canvas"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><defs><filter id="glow"><feGaussianBlur stdDeviation=".55" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>${lines}</svg><div class="topology-core"><span class="core-signal"></span><strong>NetWatch</strong><small>NETWORK CORE</small></div>${nodes}<div class="canvas-corner canvas-corner-tl">ALL ${devices.length} NODES VISIBLE</div><div class="canvas-corner canvas-corner-br">AUTO FIT</div></div><div class="topology-legend"><span><i class="legend-dot online"></i>在线</span><span><i class="legend-dot degraded"></i>SNMP 异常</span><span><i class="legend-dot offline"></i>未响应</span><span>全部节点限制在当前画布内；当前为设备清单关系，尚未自动发现 LLDP/CDP 物理链路。</span></div></section>`;}
function render(){document.body.classList.toggle('topology-view',view==='topology'&&!selected);document.body.classList.toggle('overview-view',view==='overview'&&!selected);$('#breadcrumb').textContent=selected?'设备详情':names[view];$('#pageTitle').textContent=selected?'设备运行详情':({overview:'网络设备监控运维平台',topology:'全屏网络拓扑',devices:'设备资产与采集管理。',alerts:'告警中心，聚焦值得处理的变化。',guide:'接入、指标与运行说明。'}[view]);$('#pageSubtitle').textContent=({overview:'设备、流量、链路、资源和告警集中展示。',topology:'全部节点自动适配当前画布，也可拖动微调位置。',devices:'设备按名称排序，支持筛选、编辑和手动采集。',alerts:'连续三次采集失败触发告警，恢复后自动关闭。',guide:'了解接入方式、指标含义与本机网络访问设置。'}[view]);$('.filterbar').classList.toggle('hidden',!!selected||view!=='devices');$('#stats').classList.toggle('hidden',!!selected||['overview','topology','guide'].includes(view));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#alertBadge').textContent=state.ActiveAlerts;let warnings=[];if(state.Warning)warnings.push(state.Warning);if(state.Devices.some(x=>x.Config.Demo))warnings.push('演示设备的数据为模拟值，不代表真实网络状态。');const stale=state.Devices.filter(x=>x.Config.Enabled&&x.Current&&Date.now()-x.Current.Time>Math.max(180000,x.Config.Interval*3000));if(stale.length)warnings.push(stale.length+' 台设备的数据已过期，请检查采集服务。');$('#notice').textContent=warnings.join(' ');$('#notice').classList.toggle('hidden',!warnings.length);renderStats();if(selected&&detail){renderDetail();return;}if(view==='topology'){renderTopology();return;}if(view==='guide'){renderGuide();return;}if(view==='alerts'){$('#content').innerHTML=alertsPanel(state.Alerts,false);return;}renderDevices();}
document.addEventListener('click',event=>{if(suppressTopologyClick&&event.target.closest('.topology-node')){event.preventDefault();event.stopImmediatePropagation();suppressTopologyClick=false;}},true);
document.addEventListener('click',async event=>{const target=event.target.closest('[data-action="reset-topology"]');if(!target)return;target.disabled=true;try{await api('topology/reset',{});topologyPositions={};state.Topology={};saveTopologyPositions();renderTopology();toast('拓扑布局已重置并保存');}catch(e){toast('重置失败：'+e.message);}finally{target.disabled=false;}});
document.addEventListener('pointerdown',event=>{const node=event.target.closest('.topology-node');if(!node)return;const canvas=node.closest('.topology-canvas');if(!canvas)return;topologyDrag={node,canvas,id:node.dataset.id,startX:event.clientX,startY:event.clientY,oldX:Number(node.dataset.x),oldY:Number(node.dataset.y),moved:false,pointerId:event.pointerId};node.classList.add('dragging');try{node.setPointerCapture(event.pointerId);}catch{}},{passive:true});
document.addEventListener('pointermove',event=>{if(!topologyDrag||event.pointerId!==topologyDrag.pointerId)return;const drag=topologyDrag,dx=event.clientX-drag.startX,dy=event.clientY-drag.startY;if(!drag.moved&&Math.hypot(dx,dy)<4)return;drag.moved=true;event.preventDefault();const rect=drag.canvas.getBoundingClientRect(),x=Math.max(12,Math.min(88,(event.clientX-rect.left)/rect.width*100)),y=Math.max(13,Math.min(87,(event.clientY-rect.top)/rect.height*100));drag.node.style.left=x+'%';drag.node.style.top=y+'%';drag.node.dataset.x=x;drag.node.dataset.y=y;topologyPositions[drag.id]={x,y};updateTopologyLines(drag.canvas);},{passive:false});
document.addEventListener('pointerup',async event=>{if(!topologyDrag||event.pointerId!==topologyDrag.pointerId)return;const drag=topologyDrag;drag.node.classList.remove('dragging');try{drag.node.releasePointerCapture(event.pointerId);}catch{}topologyDrag=null;if(drag.moved){suppressTopologyClick=true;setTimeout(()=>{suppressTopologyClick=false;},0);const position=topologyPositions[drag.id];try{const saved=await api('topology',{Id:drag.id,X:position.x,Y:position.y});topologyPositions[drag.id]={x:saved.x,y:saved.y};state.Topology={...(state.Topology||{}),[drag.id]:{x:saved.x,y:saved.y}};saveTopologyPositions();toast('拓扑位置已自动保存');}catch(e){topologyPositions[drag.id]={x:drag.oldX,y:drag.oldY};state.Topology={...(state.Topology||{}),[drag.id]:{x:drag.oldX,y:drag.oldY}};renderTopology();toast('位置保存失败：'+e.message);}}});
if($('#serverAddress'))$('#serverAddress').textContent=location.host;

